### ISSUE TITLE
Command line usage

### ISSUE THREAD

**Issue by himal-mandalia** [ministryofjustice/nomis-api-client-ruby#1]
Document in README command line usage of gem as a shell utility to generate a bearer token, with appropriate "gem install nomis-api-client-ruby".

**Comment by aldavidson** [comment]
Done in https://github.com/ministryofjustice/nomis-api-client-ruby/commit/a8c852bf1d1c89c6e899d00f81307c3f25a06382#diff-04c6e90faac2675aa89e2176d2eec7d8R83
